class Box{
	public static void main(String[] args){
	String[] Boxes={"blue","yellow","white","pink","dark blue","green","dark green","black","purple","saffaron","orange","silver","brown","milkyway","gold","pink","red","turquoise","teal","maroon","lavender","olive","gold","peach","grey","violet","navy","amber","mint","beige"};
	System.out.println("The box color @ 0 is -->"+Boxes[0]);
	System.out.println("The box color @ 1 is -->"+Boxes[1]);
	System.out.println("The box color @ 2 is -->"+Boxes[2]);
	System.out.println("The box color @ 3 is -->"+Boxes[3]);
	System.out.println("The box color @ 4 is -->"+Boxes[4]);
	System.out.println("The box color @ 5 is -->"+Boxes[5]);
	System.out.println("The box color @ 6 is -->"+Boxes[6]);
	System.out.println("The box color @ 7 is -->"+Boxes[7]);
	System.out.println("The box color @ 8 is -->"+Boxes[8]);
	System.out.println("The box color @ 9 is -->"+Boxes[9]);
	System.out.println("The box color @ 10 is -->"+Boxes[10]);
	System.out.println("The box color @ 11 is -->"+Boxes[11]);
	System.out.println("The box color @ 12 is -->"+Boxes[12]);
	System.out.println("The box color @ 13 is -->"+Boxes[13]);
	System.out.println("The box color @ 14 is -->"+Boxes[14]);
	System.out.println("The box color @ 15 is -->"+Boxes[15]);
	System.out.println("The box color @ 16 is -->"+Boxes[16]);
	System.out.println("The box color @ 17 is -->"+Boxes[17]);
	System.out.println("The box color @ 18 is -->"+Boxes[18]);
	System.out.println("The box color @ 19 is -->"+Boxes[19]);
	System.out.println("The box color @ 20 is -->"+Boxes[20]);
	System.out.println("The box color @ 21 is -->"+Boxes[21]);
	System.out.println("The box color @ 22 is -->"+Boxes[22]);
	System.out.println("The box color @ 23 is -->"+Boxes[23]);
	System.out.println("The box color @ 24 is -->"+Boxes[24]);
	System.out.println("The box color @ 25 is -->"+Boxes[25]);
	System.out.println("The box color @ 26 is -->"+Boxes[26]);
	System.out.println("The box color @ 27 is -->"+Boxes[27]);
	System.out.println("The box color @ 28 is -->"+Boxes[28]);
	System.out.println("The box color @ 29 is -->"+Boxes[29]);
	System.out.println("\n");
	Boxes[0]="coral";
	Boxes[1]="lilac";
	Boxes[2]="salmon";
	Boxes[3]="beige";
	Boxes[4]="Burgundy";
	Boxes[5]="Tan";
	Boxes[6]="dark brown";
	Boxes[7]="cream";
	Boxes[8]="mauve";
	Boxes[9]="plum";
	Boxes[10]="sea foram";
	Boxes[11]="periwinkle";
	Boxes[12]="sea foam";
	Boxes[13]="turquoise";
	Boxes[14]="cobalt";
	Boxes[15]="rust";
	Boxes[17]="olive";
	Boxes[18]="hunter";
	Boxes[19]="camel";
	Boxes[20]="copper";
	Boxes[21]="chartreuse";
	Boxes[22]="celery";
	Boxes[23]="teal";
	Boxes[24]="emerald";
	Boxes[25]="light blue";
	Boxes[26]="plum";
	Boxes[27]="charcoal";
	Boxes[28]="blue-green";
	Boxes[29]="mauve-violet";
	System.out.println("Here Updated Boxes colours--->");
	System.out.println("\n");
	System.out.println("The box color @ 0 is -->"+Boxes[0]);
	System.out.println("The box color @ 1 is -->"+Boxes[1]);
	System.out.println("The box color @ 2 is -->"+Boxes[2]);
	System.out.println("The box color @ 3 is -->"+Boxes[3]);
	System.out.println("The box color @ 4 is -->"+Boxes[4]);
	System.out.println("The box color @ 5 is -->"+Boxes[5]);
	System.out.println("The box color @ 6 is -->"+Boxes[6]);
	System.out.println("The box color @ 7 is -->"+Boxes[7]);
	System.out.println("The box color @ 8 is -->"+Boxes[8]);
	System.out.println("The box color @ 9 is -->"+Boxes[9]);
	System.out.println("The box color @ 10 is -->"+Boxes[10]);
	System.out.println("The box color @ 11 is -->"+Boxes[11]);
	System.out.println("The box color @ 12 is -->"+Boxes[12]);
	System.out.println("The box color @ 13 is -->"+Boxes[13]);
	System.out.println("The box color @ 14 is -->"+Boxes[14]);
	System.out.println("The box color @ 15 is -->"+Boxes[15]);
	System.out.println("The box color @ 16 is -->"+Boxes[16]);
	System.out.println("The box color @ 17 is -->"+Boxes[17]);
	System.out.println("The box color @ 18 is -->"+Boxes[18]);
	System.out.println("The box color @ 19 is -->"+Boxes[19]);
	System.out.println("The box color @ 20 is -->"+Boxes[20]);
	System.out.println("The box color @ 21 is -->"+Boxes[21]);
	System.out.println("The box color @ 22 is -->"+Boxes[22]);
	System.out.println("The box color @ 23 is -->"+Boxes[23]);
	System.out.println("The box color @ 24 is -->"+Boxes[24]);
	System.out.println("The box color @ 25 is -->"+Boxes[25]);
	System.out.println("The box color @ 26 is -->"+Boxes[26]);
	System.out.println("The box color @ 27 is -->"+Boxes[27]);
	System.out.println("The box color @ 28 is -->"+Boxes[28]);
	System.out.println("The box color @ 29 is -->"+Boxes[29]);
   }
}
