class DistFinRunner{
	
	public static void main(String[] args){
		String s="Challekere";
		String d="bng";
		int dist=DistFin.getDistanceBySourceAndDestination(s,d);
		System.out.println("dist from "+s+"to"+d+"is"+dist);
		String s1="Challekere";
		String d1="durga";
		int dist1=DistFin.getDistanceBySourceAndDestination(s1,d1);
		System.out.println("dist from "+s1+"to"+d1+"is"+dist1);
		String s2="Challekere";
		String d2="ballary";
		int dist2=DistFin.getDistanceBySourceAndDestination(s2,d2);
		System.out.println("dist from "+s2+"to"+d2+"is"+dist2);
		String s3="Challekere";
		String d3="Pavagada";
		int dist3=DistFin.getDistanceBySourceAndDestination(s3,d3);
		System.out.println("dist from "+s3+"to"+d3+"is"+dist3);
		String s4="Challekere";
		String d4="Davanagere";
		int dist4=DistFin.getDistanceBySourceAndDestination(s4,d4);
		System.out.println("dist from "+s4+"to"+d4+"is"+dist4);
		String s5="Challekere";
		String d5="Hiriyur";
		int dist5=DistFin.getDistanceBySourceAndDestination(s5,d5);
		System.out.println("dist from "+s5+"to"+d5+"is"+dist5);
		String s6="Challekere";
		String d6="Tumkur";
		int dist6=DistFin.getDistanceBySourceAndDestination(s6,d6);
		System.out.println("dist from "+s6+"to"+d6+"is"+dist6);
		String s7="Challekere";
		String d7="sira";
		int dist7=DistFin.getDistanceBySourceAndDestination(s7,d7);
		System.out.println("dist from "+s7+"to"+d7+"is"+dist7);
		String s8="Challekere";
		String d8="pune";
		int dist8=DistFin.getDistanceBySourceAndDestination(s8,d8);
		System.out.println("dist from "+s8+"to"+d8+"is"+dist8);
		String s9="Challekere";
		String d9="gujaratha";
		int dist9=DistFin.getDistanceBySourceAndDestination(s9,d9);
		System.out.println("dist from "+s9+"to"+d9+"is"+dist9);
		String s10="Challekere";
		String d10="rajasthan";
		int dist10=DistFin.getDistanceBySourceAndDestination(s10,d10);
		System.out.println("dist from "+s10+"to"+d10+"is"+dist10);
		String s11="Challekere";
		String d11="kalyanadurga";
		int dist11=DistFin.getDistanceBySourceAndDestination(s11,d11);
		System.out.println("dist from "+s11+"to"+d11+"is"+dist11);
		String s12="Challekere";
		String d12="rayadurga";
		int dist12=DistFin.getDistanceBySourceAndDestination(s12,d12);
		System.out.println("dist from "+s12+"to"+d12+"is"+dist12);
		String s13="Challekere";
		String d13="Doddaullarthy";
		int dist13=DistFin.getDistanceBySourceAndDestination(s13,d13);
		System.out.println("dist from "+s13+"to"+d13+"is"+dist13);
		String s14="Challekere";
		String d14="gadaga";
		int dist14=DistFin.getDistanceBySourceAndDestination(s14,d14);
		System.out.println("dist from "+s14+"to"+d14+"is"+dist14);
		String s15="Challekere";
		String d15="Raichuru";
		int dist15=DistFin.getDistanceBySourceAndDestination(s15,d15);
		System.out.println("dist from "+s15+"to"+d15+"is"+dist15);
		String s16="Challekere";
		String d16="Mangalore";
		int dist16=DistFin.getDistanceBySourceAndDestination(s16,d16);
		System.out.println("dist from "+s16+"to"+d16+"is"+dist16);
		String s17="Challekere";
		String d17="Dandeli";
		int dist17=DistFin.getDistanceBySourceAndDestination(s17,d17);
		System.out.println("dist from "+s17+"to"+d17+"is"+dist17);
		String s18="Challekere";
		String d18="Hampi";
		int dist18=DistFin.getDistanceBySourceAndDestination(s18,d18);
		System.out.println("dist from "+s18+"to"+d18+"is"+dist18);
		String s19="Challekere";
		String d19="Hospate";
		int dist19=DistFin.getDistanceBySourceAndDestination(s19,d19);
		System.out.println("dist from "+s19+"to"+d19+"is"+dist19);
		String s20="Challekere";
		String d20="vijayanagara";
		int dist20=DistFin.getDistanceBySourceAndDestination(s20,d20);
		System.out.println("dist from "+s20+"to"+d20+"is"+dist20);
		String s21="Challekere";
		String d21="Dharawad";
		int dist21=DistFin.getDistanceBySourceAndDestination(s21,d21);
		System.out.println("dist from "+s21+"to"+d21+"is"+dist21);
		String s22="Challekere";
		String d22="karawalli";
		int dist22=DistFin.getDistanceBySourceAndDestination(s22,d22);
		System.out.println("dist from "+s22+"to"+d22+"is"+dist22);
		
	}
}