class CountryRunner{
public static void main(String[] args){
String name="India";
Country.Population(name);
name="China";
Country.Population(name);
name="United States	";
Country.Population(name);
name="Indonesia";
Country.Population(name);
name="Pakistan";
Country.Population(name);
name="Nigeria";
Country.Population(name);
name="Brazil";
Country.Population(name);
name="Bangladesh";
Country.Population(name);
name="Russia";
Country.Population(name);
name="Mexico";
Country.Population(name);
name="Japan";
Country.Population(name);
name="Ethiopia";
Country.Population(name);
name="Philippines	";
Country.Population(name);
name="Egypt";
Country.Population(name);
name="Vietnam";
Country.Population(name);
name="DR Congo";
Country.Population(name);
name="Turkey";
Country.Population(name);
name="Iran";
Country.Population(name);
name="Germany";
Country.Population(name);
name="Thailand";
Country.Population(name);
name="United Kingdom";
Country.Population(name);
name="France";
Country.Population(name);
name="Italy";
Country.Population(name);
name="South Africa";
Country.Population(name);
name="Tanzania";
Country.Population(name);
name="Myanmar";
Country.Population(name);
name="South Korea";
Country.Population(name);
name="Colombia";
Country.Population(name);
name="Kenya";
Country.Population(name);
name="Spain";
Country.Population(name);
name="Argentina";
Country.Population(name);
name="Algeria";
Country.Population(name);
name="Ukraine";
Country.Population(name);
name="Sudan";
Country.Population(name);
name="Uganda";
Country.Population(name);
name="Iraq";
Country.Population(name);
name="Poland";
Country.Population(name);
name="Canada";
Country.Population(name);
name="Morocco";
Country.Population(name);
name="Saudi Arabia";
Country.Population(name);
name="Uzbekistan";
Country.Population(name);
name="Peru";
Country.Population(name);
name="Malaysia";
Country.Population(name);
name="Angola";
Country.Population(name);
name="Ghana";
Country.Population(name);
name="Mozambique";
Country.Population(name);
name="Yemen";
Country.Population(name);
name="Nepal";
Country.Population(name);
name="Venezuela";
Country.Population(name);
name="Madagascar";
Country.Population(name);
name="Cameroon";
Country.Population(name);
name="Côte d'Ivoire";
Country.Population(name);
name="North Korea";
Country.Population(name);
name="Australia";
Country.Population(name);
name="Niger";
Country.Population(name);
name="Sri Lanka";
Country.Population(name);
name="Burkina Faso";
Country.Population(name);
name="Mali";
Country.Population(name);
name="Malawi";
Country.Population(name);
name="Zambia";
Country.Population(name);
name="Syria";
Country.Population(name);
name="Kazakhstan";
Country.Population(name);
name="Chile";
Country.Population(name);
name="Guatemala";
Country.Population(name);
name="Senegal";
Country.Population(name);
name="Chad";
Country.Population(name);
name="Somalia";
Country.Population(name);
name="Zimbabwe";
Country.Population(name);
name="Cambodia";
Country.Population(name);
name="South Sudan";
Country.Population(name);
name="Rwanda";
Country.Population(name);
name="Tunisia";
Country.Population(name);
name="Guinea";
Country.Population(name);
name="Benin";
Country.Population(name);
name="Bolivia";
Country.Population(name);
name="Belgium";
Country.Population(name);
name="Haiti";
Country.Population(name);
name="Burundi";
Country.Population(name);
name="Cuba";
Country.Population(name);
name="Greece";
Country.Population(name);
name="Jordan";
Country.Population(name);
name="Czech Republic";
Country.Population(name);
name="Dominican Republic";
Country.Population(name);
name="Sweden";
Country.Population(name);
name="Portugal";
Country.Population(name);
name="Azerbaijan";
Country.Population(name);
name="IndiaHungary";
Country.Population(name);
name="Belarus";
Country.Population(name);
name="United Arab Emirates";
Country.Population(name);
name="Israel";
Country.Population(name);
name="Honduras";
Country.Population(name);
name="Tajikistan";
Country.Population(name);
name="Papua New Guinea";
Country.Population(name);
name="Austria";
Country.Population(name);
name="Switzerland";
Country.Population(name);
name="Sierra Leone	";
Country.Population(name);
name="Togo";
Country.Population(name);
name="Hong Kong";
Country.Population(name);
name="Laos";
Country.Population(name);
name="Paraguay";
Country.Population(name);
name="Bulgaria";
Country.Population(name);
name="Bulgaria";
Country.Population(name);
name="Libya";
Country.Population(name);
name="El Salvador";
Country.Population(name);
name="Nicaragua";
Country.Population(name);
name="Lebanon";
Country.Population(name);
name="New Zealand";
Country.Population(name);
name="Mauritania";
Country.Population(name);
name="Panama";
Country.Population(name);
name="Kuwait";
Country.Population(name);
name="Croatia";
Country.Population(name);
name="Moldova";
Country.Population(name);
name="Georgia";
Country.Population(name);
name="Eritrea";
Country.Population(name);
name="Uruguay";
Country.Population(name);
name="Mongolia";
Country.Population(name);
name="Bosnia and Herzegovina";
Country.Population(name);
name="Armenia";
Country.Population(name);
name="Jamaica";
Country.Population(name);
name="Qatar";
Country.Population(name);
name="Albania";
Country.Population(name);
name="Puerto Rico";
Country.Population(name);
name="Lithuania";
Country.Population(name);
name="Namibia";
Country.Population(name);
name="Gambia";
Country.Population(name);
name="Botswana";
Country.Population(name);
name="Gabon";
Country.Population(name);
name="Lesotho";
Country.Population(name);
name="North Macedonia";
Country.Population(name);
name="Slovenia";
Country.Population(name);
name="Guinea-Bissau";
Country.Population(name);
name="Latvia";
Country.Population(name);
name="Bahrain";
Country.Population(name);
name="Equatorial Guinea";
Country.Population(name);
name="Trinidad and Tobago";
Country.Population(name);
name="Estonia";
Country.Population(name);
name="Timor-Leste";
Country.Population(name);
name="Mauritius";
Country.Population(name);
name="Cyprus";
Country.Population(name);
name="Eswatini";
Country.Population(name);
name="Djibouti";
Country.Population(name);
name="Fiji";
Country.Population(name);
name="Réunion";
Country.Population(name);
name="Comoros";
Country.Population(name);
name="Guyana";
Country.Population(name);
name="Bhutan";
Country.Population(name);
name="Solomon Islands";
Country.Population(name);
name="Macao";
Country.Population(name);
name="Montenegro";
Country.Population(name);
name="Luxembourg";
Country.Population(name);
name="Western Sahara";
Country.Population(name);
name="Suriname";
Country.Population(name);
name="Cabo Verde";
Country.Population(name);
name="Micronesia";
Country.Population(name);
name="Malta";
Country.Population(name);
name="Maldives";
Country.Population(name);
name="Brunei";
Country.Population(name);
name="Guadeloupe";
Country.Population(name);
name="Belize";
Country.Population(name);
name="Bahamas";
Country.Population(name);
name="Martinique";
Country.Population(name);
name="Iceland";
Country.Population(name);
name="Vanuatu";
Country.Population(name);
name="French Guiana";
Country.Population(name);
name="Barbados";
Country.Population(name);
name="New Caledonia";
Country.Population(name);
name="French Polynesia";
Country.Population(name);
name="Mayotte";
Country.Population(name);
name="Sao Tome and Principe";
Country.Population(name);
name="Samoa";
Country.Population(name);
name="Saint Lucia";
Country.Population(name);
name="Channel Islands";
Country.Population(name);
name="Guam";
Country.Population(name);
name="Curaçao";
Country.Population(name);
name="Kiribati";
Country.Population(name);
name="Grenada";
Country.Population(name);
name="St. Vincent and the Grenadines";
Country.Population(name);
name="Aruba";
Country.Population(name);
name="Tonga";
Country.Population(name);
name="US Virgin Islands";
Country.Population(name);
name="Seychelles";
Country.Population(name);
name="Antigua and Barbuda";
Country.Population(name);
name="Isle of Man";
Country.Population(name);
name="Andorra";
Country.Population(name);
name="Dominica";
Country.Population(name);
name="Cayman Islands";
Country.Population(name);
name="Bermuda";
Country.Population(name);
name="Marshall Islands";
Country.Population(name);
name="Northern Mariana Islands";
Country.Population(name);
name="Greenland";
Country.Population(name);
name="American Samoa";
Country.Population(name);
name="Saint Kitts and Nevis";
Country.Population(name);
name="Faroe Islands";
Country.Population(name);
name="Sint Maarten";
Country.Population(name);
name="Liechtenstein";
Country.Population(name);
}}
