package com.inheritance.overriding.Runner;

import com.inheritance.overriding.internal.*;

public class Runner {
    public static void main(String[] args) {
        // for tv
        TV tv=new TV(121,"LGtv");

        tv.tvdisplay();

        //TV ptv=new ProTv();
//        ptv.usetv();
//        ProTv proTv=new ProTv();
//        proTv.usetv();
//        proTv.maintaintv();
//        SonyTV sonyTV=new SonyTV();
//        sonyTV.show(tv);
//        sonyTV.show(proTv);
        System.out.println("===============================================================");
        //laptop
        Laptop laptop=new Laptop(100,"HP");

        laptop.lapdisplay();

//        Laptop laptop1=new SmartLaptop();
//        laptop1.uselaptop();
//        SmartLaptop smartLaptop=new SmartLaptop();
//        smartLaptop.maintainlaptop();
//        smartLaptop.uselaptop();
//        AsusLaptop asusLaptop=new AsusLaptop();
//        asusLaptop.asusshow(laptop);
//        asusLaptop.asusshow(laptop1);
        System.out.println("===============================================================");

        //smartphone
        SmartPhone smartPhone=new SmartPhone(134,"One Plus");

        smartPhone.smartdisp();
       // smartPhone.usesmartphone();
//        SmartPhone smartPhone1=new MaxSmartphone();
//        smartPhone1.usesmartphone();
//        MaxSmartphone maxSmartphone=new MaxSmartphone();
//        maxSmartphone.maintainsmartphone();
//        maxSmartphone.usesmartphone();
//        OnePlusPhone onePlusPhone=new OnePlusPhone();
//        onePlusPhone.phoneshow(smartPhone);
//        onePlusPhone.phoneshow(smartPhone1);
        System.out.println("===============================================================");
        //for camera
        Camera camera=new Camera(121,"sony");
        camera.camdisp();
//        camera.usecamera();
//        Camera camera1=new MaxCamera();
//        camera1.usecamera();
//        MaxCamera maxCamera=new MaxCamera();
//        maxCamera.usecamera();
//        maxCamera.maitaincamera();
//        PruthviCamera pruthviCamera=new PruthviCamera();
//        pruthviCamera.camshow(camera);
//        pruthviCamera.camshow(camera1);
        System.out.println("===============================================================");
        //Refrigerator
        Refrigerator refrigerator=new Refrigerator(132,"Sumsung");
        refrigerator.refname();
//        refrigerator.useref();
//        Refrigerator refrigerator1=new UltraRefrigerator();
//        refrigerator1.useref();
//        UltraRefrigerator ultraRefrigerator=new UltraRefrigerator();
//        ultraRefrigerator.useref();
//        ultraRefrigerator.maintainRef();
//        ProRefrigerator proRefrigerator=new ProRefrigerator();
//        proRefrigerator.proshow(refrigerator);
//        proRefrigerator.proshow(refrigerator1);
        System.out.println("===============================================================");
        //WashingMachine
        WashingMachine washingMachine=new WashingMachine(100,"Elite");
        washingMachine.washdisp();
//        washingMachine.usewashmachine();
//        WashingMachine washingMachine1=new EliteWashingMachine();
//        washingMachine1.usewashmachine();
//        EliteWashingMachine eliteWashingMachine=new EliteWashingMachine();
//        eliteWashingMachine.usewashmachine();
//        eliteWashingMachine.maintainwashingmachine();
//        ProWashingMachine proWashingMachine=new ProWashingMachine();
//        proWashingMachine.showwash(washingMachine);
//        proWashingMachine.showwash(washingMachine1);
        System.out.println("===============================================================");
        //AirConditioner
        AirConditioner airConditioner=new AirConditioner(200,"MI");
        airConditioner.airdisp();
//        airConditioner.useaircondtioner();
//        AirConditioner airConditioner1=new MaxAirConditioner();
//        airConditioner1.useaircondtioner();
//        MaxAirConditioner maxAirConditioner=new MaxAirConditioner();
//        maxAirConditioner.useaircondtioner();
//        maxAirConditioner.maintianairconditioner();
//        ProAirConditioner proAirConditioner=new ProAirConditioner();
//        proAirConditioner.airshow(airConditioner);
//        proAirConditioner.airshow(airConditioner1);
        System.out.println("===============================================================");
        //Microwave
        Microwave microwave=new Microwave(315,"Godrej");
        microwave.micdisp();
//        microwave.usemicrowave();
//        Microwave microwave1=new UltraMicrowave();
//        microwave1.usemicrowave();
//        UltraMicrowave ultraMicrowave=new UltraMicrowave();
//        ultraMicrowave.usemicrowave();
//        ultraMicrowave.maintainmicrowave();
//        ProMicrowave proMicrowave=new ProMicrowave();
//        proMicrowave.microshow(microwave);
//        proMicrowave.microshow(microwave1);
        System.out.println("===============================================================");
        //Printer
        Printer printer=new Printer(121,"Pruthvi");
        printer.pridisp();
//        printer.useprinter();
//        Printer printer1=new MaxPrinter();
//        printer1.useprinter();
//        MaxPrinter maxPrinter=new MaxPrinter();
//        maxPrinter.useprinter();
//        maxPrinter.mainprinter();
//        ProPrinter printer2=new ProPrinter();
//        printer2.prishow(printer);
//        printer2.prishow(printer1);
        System.out.println("===============================================================");
        //Speaker
        Speaker speaker=new Speaker(222,"JBL");
        speaker.spekdisp();
//        speaker.useseaker();
//        Speaker speaker1=new ProSpeaker();
//        speaker1.useseaker();
//        ProSpeaker proSpeaker=new ProSpeaker();
//        proSpeaker.useseaker();
//        proSpeaker.mainseaker();
//        UltraSpeaker ultraSpeaker=new UltraSpeaker();
//        ultraSpeaker.speak(speaker);
//        ultraSpeaker.speak(speaker1);
        System.out.println("===============================================================");
        SmartWatch smartWatch=new SmartWatch(101,"Titan");
        smartWatch.smartdisp();
//        smartWatch.usesmartwatch();
//        SmartWatch smartWatch1=new EliteSmartWatch();
//        EliteSmartWatch eliteSmartWatch=new EliteSmartWatch();
//        eliteSmartWatch.usesmartwatch();
//        eliteSmartWatch.mainsmartwatch();
//        ProSmartWatch proSmartWatch=new ProSmartWatch();
//        proSmartWatch.watchshow(smartWatch);
//        proSmartWatch.watchshow(smartWatch1);
        System.out.println("===============================================================");
        Router router=new Router(1200,"airtel");
        router.routdisp();
//        router.userouter();
//        Router router1=new MaxRouter();
//        router1.userouter();
//        MaxRouter maxRouter=new MaxRouter();
//        maxRouter.userouter();
//        maxRouter.mainrouter();
//        ProRouter proRouter=new ProRouter();
//        proRouter.routershow(router);
//        proRouter.routershow(router1);
        System.out.println("===============================================================");
        Tablet tablet=new Tablet(12,"Dolo");
        tablet.tabdisp();
//        tablet.usetablet();
//        Tablet tablet1=new SmartTablet();
//        tablet1.usetablet();
//        SmartTablet smartTablet=new SmartTablet();
//        smartTablet.usetablet();
//        smartTablet.maintablet();
//        ProTablet proTablet=new ProTablet();
//        proTablet.tabshow(tablet);
//        proTablet.tabshow(tablet1);
        System.out.println("===============================================================");
        Drone drone=new Drone(4,"DJI");
        drone.winddisp();
//        drone.usedrone();
//        Drone drone1=new UltraDrone();
//        UltraDrone ultraDrone=new UltraDrone();
//        ultraDrone.usedrone();
//        ultraDrone.maindrone();
//        ProDrone proDrone=new ProDrone();
//        proDrone.droneshow(drone);
//        proDrone.droneshow(drone1);
        System.out.println("===============================================================");
        Projector projector=new Projector(1400,"Epson");
        projector.prodisp();
//        projector.useprojector();
//        Projector projector1=new ProProjector();
//        projector1.useprojector();
//        ProProjector projector2=new ProProjector();
//        projector2.useprojector();
//        projector2.mainprojector();
//        UltraProProjector ultraProProjector=new UltraProProjector();
//        ultraProProjector.showprojector(projector);
//        ultraProProjector.showprojector(projector1);
        System.out.println("===============================================================");
        VacuumCleaner vacuumCleaner=new VacuumCleaner(98,"Vlog");
        vacuumCleaner.vacdisp();
//        vacuumCleaner.usevaccum();
//        VacuumCleaner vacuumCleaner1=new SmartVacuumCleaner();
//        vacuumCleaner1.usevaccum();
//        SmartVacuumCleaner smartVacuumCleaner=new SmartVacuumCleaner();
//        smartVacuumCleaner.usevaccum();
//        smartVacuumCleaner.mainvaccumn();
//        ProVacuumCleaner proVacuumCleaner=new ProVacuumCleaner();
//        proVacuumCleaner.vacuumshow(vacuumCleaner);
//        proVacuumCleaner.vacuumshow(vacuumCleaner1);
        System.out.println("===============================================================");
        SmartLight smartLight=new SmartLight(88,"Hepson");
        smartLight.smartdisp();
//        smartLight.usesmartlight();
//        SmartLight smartLight1=new EliteSmartLight();
//        smartLight1.usesmartlight();
//        EliteSmartWatch eliteSmartWatch1=new EliteSmartWatch();
//        eliteSmartWatch1.usesmartwatch();
//        eliteSmartWatch1.mainsmartwatch();
//        ProSmartLight proSmartLight=new ProSmartLight();
//        proSmartLight.lightshow(smartLight);
//        proSmartLight.lightshow(smartLight1);
        System.out.println("===============================================================");
        CoffeeMaker coffeeMaker=new CoffeeMaker(23,"Bru");
        coffeeMaker.coffdisp();
//        coffeeMaker.usecoffe();
//        CoffeeMaker coffeeMaker1=new UltraCoffeeMaker();
//        coffeeMaker1.usecoffe();
//        UltraCoffeeMaker ultraCoffeeMaker=new UltraCoffeeMaker();
//        ultraCoffeeMaker.usecoffe();
//        ultraCoffeeMaker.maincoffee();
//        ProCoffeeMaker proCoffeeMaker=new ProCoffeeMaker();
//        proCoffeeMaker.showcoffee(coffeeMaker);
//        proCoffeeMaker.showcoffee(coffeeMaker1);
        System.out.println("===============================================================");
        Oven oven=new Oven(99,"Sun");
        oven.ovendisp();
//        oven.useoven();
//        Oven oven1=new MaxOven();
//        oven1.useoven();
//        MaxOven maxOven=new MaxOven();
//        maxOven.useoven();
//        maxOven.mainoven();
//        ProOven proOven=new ProOven();
//        proOven.showoven(oven);
//        proOven.showoven(oven1);
        System.out.println("===============================================================");
        Toaster toaster=new Toaster(88,"MI");
        toaster.toastdisp();
//        toaster.usetoaster();
//        Toaster toaster1=new ProToaster();
//        toaster1.usetoaster();
//        ProToaster proToaster=new ProToaster();
//        proToaster.usetoaster();
//        proToaster.maintoster();
//        UltraToaster ultraToaster=new UltraToaster();
//        ultraToaster.showtoster(toaster);
//        ultraToaster.showtoster(toaster1);
        System.out.println("===============================================================");
        Blender blender=new Blender(99,"Blender 11");
//        blender.useblender();
//        Blender blender1=new UltraBlender();
//        blender1.useblender();
//        UltraBlender ultraBlender=new UltraBlender();
//        ultraBlender.useblender();
//        ultraBlender.mainbleder();
//        ProBlender proBlender=new ProBlender();
//        proBlender.showblender(blender);
//        proBlender.showblender(blender1);
        System.out.println("===============================================================");
        ElectricKettle electricKettle=new ElectricKettle(89,"HIT");
        electricKettle.kettledisp();
//        electricKettle.usekettle();
//        ElectricKettle electricKettle1=new SmartElectricKettle();
//        electricKettle1.usekettle();
//        SmartElectricKettle smartElectricKettle=new SmartElectricKettle();
//        smartElectricKettle.usekettle();
//        smartElectricKettle.mainkettle();
//        ProElectricKettle proElectricKettle=new ProElectricKettle();
//        proElectricKettle.showkettle(electricKettle);
//        proElectricKettle.showkettle(electricKettle1);
        System.out.println("===============================================================");
        HairDryer hairDryer=new HairDryer(99,"Pruthvi123");
        hairDryer.hairdryerdisp();
//        hairDryer.usehairdryer();
//        HairDryer hairDryer1=new MaxHairDryer();
//        hairDryer1.usehairdryer();
//        MaxHairDryer maxHairDryer=new MaxHairDryer();
//        maxHairDryer.mainhairdryer();
//        maxHairDryer.usehairdryer();
//        ProHairDryer proHairDryer=new ProHairDryer();
//        proHairDryer.showdriver(hairDryer);
//        proHairDryer.showdriver(hairDryer1);
        System.out.println("===============================================================");
        Heater heater=new Heater(23,"cold");
        heater.heaterdisp();
//        heater.useheater();
//        Heater heater1=new EliteHeater();
//        heater1.useheater();
//        EliteHeater eliteHeater=new EliteHeater();
//        eliteHeater.useheater();
//        eliteHeater.mainheater();
//        ProHeater proHeater=new ProHeater();
//        proHeater.showheat(heater);
//        proHeater.showheat(heater1);
        System.out.println("===============================================================");
        GameConsole gameConsole=new GameConsole("100Serires","JOY");
        gameConsole.consoledisp();
//        gameConsole.useconsole();
//        GameConsole gameConsole1=new SmartGameConsole();
//        gameConsole1.useconsole();
//        SmartGameConsole smartGameConsole=new SmartGameConsole();
//        smartGameConsole.mainconsole();
//        smartGameConsole.useconsole();
//        ProGameConsole proGameConsole=new ProGameConsole();
//        proGameConsole.showgame(gameConsole);
//        proGameConsole.showgame(gameConsole1);
        System.out.println("===============================================================");
        Monitor monitor=new Monitor(32,"1480");
        monitor.monitordisp();
//        monitor.usemonitor();
//        Monitor monitor1=new UltraMonitor();
//        monitor1.usemonitor();
//        UltraMonitor ultraMonitor=new UltraMonitor();
//        ultraMonitor.usemonitor();
//        ultraMonitor.mainmonitor();
//        ProMonitor proMonitor=new ProMonitor();
//        proMonitor.showmonitor(monitor);
//        proMonitor.showmonitor(monitor1);
        System.out.println("===============================================================");
        FitnessTracker fitnessTracker=new FitnessTracker("MI",1000);
        fitnessTracker.trackerdisp();
//        fitnessTracker.usetracker();
//        FitnessTracker fitnessTracker1=new MaxFitnessTracker();
//        fitnessTracker1.usetracker();
//        MaxFitnessTracker maxFitnessTracker=new MaxFitnessTracker();
//        maxFitnessTracker.usetracker();
//        maxFitnessTracker.maintracker();
//        ProFitnessTracker proFitnessTracker=new ProFitnessTracker();
//        proFitnessTracker.showfit(fitnessTracker);
//        proFitnessTracker.showfit(fitnessTracker1);
        System.out.println("===============================================================");
        Fan fan=new Fan(360,"Butterfly");
        fan.fandisp();
//        fan.usefan();
//        Fan fan1=new SmartFan();
//        fan1.usefan();
//        SmartFan smartFan=new SmartFan();
//        smartFan.usefan();
//        smartFan.mainfan();
//        ProFan proFan=new ProFan();
//        proFan.showfan(fan);
//        proFan.showfan(fan1);
        System.out.println("===============================================================");
        Iron iron=new Iron(50,"TMT");
        iron.irondisp();
//        iron.useiron();
//        Iron iron1=new ProIron();
//        iron1.useiron();
//        ProIron proIron=new ProIron();
//        proIron.useiron();
//        proIron.mainiron();
//        SmartIron smartIron=new SmartIron();
//        smartIron.showriron(iron);
//        smartIron.showriron(iron1);
        System.out.println("===============================================================");
        SmartDoorbell smartDoorbell=new SmartDoorbell("sony",true);
        smartDoorbell.doorbelldisp();
//        smartDoorbell.usrdoorbell();
//        SmartDoorbell smartDoorbell1=new EliteSmartDoorbell();
//        smartDoorbell1.usrdoorbell();
//        EliteSmartDoorbell eliteSmartDoorbell=new EliteSmartDoorbell();
//        eliteSmartDoorbell.usrdoorbell();
//        eliteSmartDoorbell.maindoorbell();
//        ProSmartDoorbell proSmartDoorbell=new ProSmartDoorbell();
//        proSmartDoorbell.showdorr(smartDoorbell);
//        proSmartDoorbell.showdorr(smartDoorbell1);
        System.out.println("===============================================================");
        SecurityCamera securityCamera=new SecurityCamera("1420",true);
        securityCamera.cameradisp();
//        securityCamera.usesecuritycamere();
//        SecurityCamera securityCamera1=new UltraSecurityCamera();
//        securityCamera1.usesecuritycamere();
//        UltraSecurityCamera ultraSecurityCamera=new UltraSecurityCamera();
//        ultraSecurityCamera.usesecuritycamere();
//        ultraSecurityCamera.mainsecuritycamera();
//        ProSecurityCamera proSecurityCamera=new ProSecurityCamera();
//        proSecurityCamera.showcamera(securityCamera);
//        proSecurityCamera.showcamera(securityCamera1);
        System.out.println("===============================================================");
        Ebike ebike=new Ebike(24,"12Series");
        ebike.ebikedisp();
//        ebike.useebike();
//        Ebike ebike1=new MaxEbike();
//        ebike1.useebike();
//        MaxEbike maxEbike=new MaxEbike();
//        maxEbike.useebike();
//        maxEbike.mainebike();
//        ProEbike proEbike=new ProEbike();
//        proEbike.showbike(ebike);
//        proEbike.showbike(ebike1);
        System.out.println("===============================================================");
        LawnMower lawnMower=new LawnMower(145,"flexible");
        lawnMower.lawndisp();
//        lawnMower.uselawnmover();
//        LawnMower lawnMower1=new SmartLawnMower();
//        lawnMower1.uselawnmover();
//        SmartLawnMower smartLawnMower=new SmartLawnMower();
//        smartLawnMower.uselawnmover();
//        smartLawnMower.mainlawnover();
//        ProLawnMower proLawnMower=new ProLawnMower();
//        proLawnMower.showlawn(lawnMower);
//        proLawnMower.showlawn(lawnMower1); 33
        System.out.println("===============================================================");
        RobotPet robotPet=new RobotPet("xiomi 100",8);
        robotPet.petdisp();
//        robotPet.userobotpet();
//        RobotPet robotPet1=new ProRobotPet();
//        robotPet1.userobotpet();
//        ProRobotPet proRobotPet=new ProRobotPet();
//        proRobotPet.userobotpet();
//        proRobotPet.mainrobotpet();
//        SmartRobotPet smartRobotPet=new SmartRobotPet();
//        smartRobotPet.showrobot(robotPet);
//        smartRobotPet.showrobot(robotPet1);
        System.out.println("===============================================================");
        ThreedPrinter threedPrinter=new ThreedPrinter("HP 200",88.00);
        threedPrinter.printerdisp();
//        threedPrinter.usethreedprinter();
//        ThreedPrinter threedPrinter1=new EliteThreedPrinter();
//        threedPrinter1.usethreedprinter();
//        EliteThreedPrinter eliteThreedPrinter=new EliteThreedPrinter();
//        eliteThreedPrinter.usethreedprinter();
//        eliteThreedPrinter.mainthreedprinter();
//        ProThreedPrinter proThreedPrinter=new ProThreedPrinter();
//        proThreedPrinter.showprint(threedPrinter);
//        proThreedPrinter.showprint(threedPrinter1);
        System.out.println("===============================================================");
        SmartMirror smartMirror=new SmartMirror("HP",true);
        smartMirror.mirrorDisp();
//        smartMirror.usemirror();
//        SmartMirror smartMirror1=new UltraSmartMirror();
//        smartMirror1.usemirror();
//        UltraSmartMirror ultraSmartMirror=new UltraSmartMirror();
//        ultraSmartMirror.usemirror();
//        ultraSmartMirror.mainmirror();
//        ProSmartMirror proSmartMirror=new ProSmartMirror();
//        proSmartMirror.showmirror(smartMirror);
//        proSmartMirror.showmirror(smartMirror1);
        System.out.println("===============================================================");
        Dishwasher dishwasher=new Dishwasher("Ultrapower 100",95);
        dishwasher.dishwasherDisp();
//        dishwasher.usedishwasher();
//        Dishwasher dishwasher1=new MaxDishwasher();
//        dishwasher1.usedishwasher();
//        MaxDishwasher maxDishwasher=new MaxDishwasher();
//        maxDishwasher.usedishwasher();
//        maxDishwasher.maindishwasher();
//        ProDishwasher proDishwasher=new ProDishwasher();
//        proDishwasher.showdish(dishwasher);
//        proDishwasher.showdish(dishwasher1);
        System.out.println("===============================================================");
        SteamMop steamMop=new SteamMop("healthy 200",85);
        steamMop.mopDisp();
//        steamMop.usemop();
//        SteamMop steamMop1=new SmartSteamMop();
//        SmartSteamMop smartSteamMop=new SmartSteamMop();
//        smartSteamMop.usemop();
//        smartSteamMop.mainmop();
//        ProSteamMop proSteamMop=new ProSteamMop();
//        proSteamMop.showmop(steamMop);
//        proSteamMop.showmop(steamMop1);
        System.out.println("===============================================================");
        BluetoothTracker bluetoothTracker=new BluetoothTracker("one plus",50);
        bluetoothTracker.trackerDisp();
//        bluetoothTracker.useblue();
//        BluetoothTracker bluetoothTracker1=new ProBluetoothTracker();
//        bluetoothTracker1.useblue();
//        ProBluetoothTracker proBluetoothTracker=new ProBluetoothTracker();
//        proBluetoothTracker.useblue();
//        proBluetoothTracker.mainblue();
//        SmartBluetoothTracker smartBluetoothTracker=new SmartBluetoothTracker();
//        smartBluetoothTracker.showblue(bluetoothTracker);
//        smartBluetoothTracker.showblue(bluetoothTracker1);
        System.out.println("===============================================================");
        ElectricScooter electricScooter=new ElectricScooter("Life 100",95);
        electricScooter.scooterDisp();
//        electricScooter.usescooter();
//        ElectricScooter electricScooter1=new MaxElectricScooter();
//        electricScooter1.usescooter();
//        MaxElectricScooter maxElectricScooter=new MaxElectricScooter();
//        maxElectricScooter.usescooter();
//        maxElectricScooter.mainscooter();
//        ProElectricScooter proElectricScooter=new ProElectricScooter();
//        proElectricScooter.showele(electricScooter);
//        proElectricScooter.showele(electricScooter1);40
        System.out.println("===============================================================");
        PowerBank powerBank=new PowerBank("MI",98);
        powerBank.powerBankDisp();
//        powerBank.usepowerbank();
//        PowerBank powerBank1=new UltraPowerBank();
//        powerBank1.usepowerbank();
//        UltraPowerBank ultraPowerBank=new UltraPowerBank();
//        ultraPowerBank.usepowerbank();
//        ultraPowerBank.mainusepowerbank();
//        ProPowerBank proPowerBank=new ProPowerBank();
//        proPowerBank.showbank(powerBank);
//        proPowerBank.showbank(powerBank1);
        System.out.println("===============================================================");
        GraphicsTablet graphicsTablet=new GraphicsTablet("Ryzen",1420);
        graphicsTablet.tabletDisp();
//        graphicsTablet.usetablet();
//        GraphicsTablet graphicsTablet1=new ProGraphicsTablet();
//        graphicsTablet1.usetablet();
//        ProGraphicsTablet proGraphicsTablet=new ProGraphicsTablet();
//        proGraphicsTablet.usetablet();
//        proGraphicsTablet.maintablet();
//        SmartGraphicsTablet smartGraphicsTablet=new SmartGraphicsTablet();
//        smartGraphicsTablet.showgraphic(graphicsTablet);
//        smartGraphicsTablet.showgraphic(graphicsTablet1);
        System.out.println("===============================================================");
        PortableAC portableAC=new PortableAC("shakthi",76);
        portableAC.portableACDisp();
//        portableAC.useportable();
//        PortableAC portableAC1=new SmartPortableAC();
//        portableAC1.useportable();
//        SmartPortableAC smartPortableAC=new SmartPortableAC();
//        smartPortableAC.useportable();
//        smartPortableAC.mainportable();
//        ProPortableAC proPortableAC=new ProPortableAC();
//        proPortableAC.showport(portableAC);
//        proPortableAC.showport(portableAC1);
        System.out.println("===============================================================");
        Dehumidifier dehumidifier=new Dehumidifier("Asus",150);
        dehumidifier.dehumidifierDisp();
//        dehumidifier.usemidifier();
//        Dehumidifier dehumidifier1=new EliteDehumidifier();
//        dehumidifier1.usemidifier();
//        EliteDehumidifier eliteDehumidifier=new EliteDehumidifier();
//        eliteDehumidifier.usemidifier();
//        eliteDehumidifier.maindiffer();
//        ProDehumidifier proDehumidifier=new ProDehumidifier();
//        proDehumidifier.showdehu(dehumidifier);
//        proDehumidifier.showdehu(dehumidifier1);
        System.out.println("===============================================================");
        AirPurifier airPurifier=new AirPurifier("Gold flag",91);
        airPurifier.airPurifierDisp();
//        airPurifier.useair();
//        AirPurifier airPurifier1=new UltraAirPurifier();
//        airPurifier1.useair();
//        UltraAirPurifier ultraAirPurifier=new UltraAirPurifier();
//        ultraAirPurifier.useair();
//        ultraAirPurifier.mainair();
//        ProAirPurifier proAirPurifier=new ProAirPurifier();
//        proAirPurifier.showair(airPurifier);
//        proAirPurifier.showair(airPurifier1);45
        System.out.println("===============================================================");
        WaterPurifier waterPurifier=new WaterPurifier("Aquagurad",100);
        waterPurifier.purifierDisp();
//        waterPurifier.usepurifier();
//        WaterPurifier waterPurifier1=new MaxWaterPurifier();
//        waterPurifier1.usepurifier();
//        MaxWaterPurifier maxWaterPurifier=new MaxWaterPurifier();
//        maxWaterPurifier.usepurifier();
//        maxWaterPurifier.mainpurifier();
//        ProWaterPurifier proWaterPurifier=new ProWaterPurifier();
//        proWaterPurifier.showwater(waterPurifier);
//        proWaterPurifier.showwater(waterPurifier1);
        System.out.println("===============================================================");
        SmartLock smartLock=new SmartLock("Godrej",true);
        smartLock.lockDisp();
//        smartLock.uselock();
//        SmartLock smartLock1=new SmartSmartLock();
//        smartLock1.uselock();
//        SmartSmartLock smartSmartLock=new SmartSmartLock();
//        smartSmartLock.mainlock();
//        smartSmartLock.uselock();
//        ProSmartLock proSmartLock=new ProSmartLock();
//        proSmartLock.showlock(smartLock);
//        proSmartLock.showlock(smartLock1);
        System.out.println("===============================================================");
        SmartGlasses smartGlasses=new SmartGlasses("apple",true);
        smartGlasses.glassesDisp();
//        smartGlasses.useglasses();
//        SmartGlasses smartGlasses1=new ProSmartGlasses();
//        smartGlasses1.useglasses();
//        ProSmartGlasses proSmartGlasses=new ProSmartGlasses();
//        proSmartGlasses.useglasses();
//        proSmartGlasses.mainglasses();
//        SmartSmartGlasses smartSmartGlasses=new SmartSmartGlasses();
//        smartSmartGlasses.showglass(smartGlasses);
//        smartSmartGlasses.showglass(smartGlasses1); 48
        System.out.println("===============================================================");
        HomeTheater homeTheater=new HomeTheater("Sumsung",10);
        homeTheater.theaterDisp();
//        homeTheater.usetheater();
//        HomeTheater homeTheater1=new EliteHomeTheater();
//        homeTheater1.usetheater();
//        EliteHomeTheater eliteHomeTheater=new EliteHomeTheater();
//        eliteHomeTheater.usetheater();
//        eliteHomeTheater.maintheater();
//        ProHomeTheater proHomeTheater=new ProHomeTheater();
//        proHomeTheater.showhome(homeTheater);
//        proHomeTheater.showhome(homeTheater1); 49
        System.out.println("===============================================================");
        BarcodeScanner barcodeScanner=new BarcodeScanner("Standard",true);
        barcodeScanner.scannerDisp();
//        barcodeScanner.usebar();
//        BarcodeScanner barcodeScanner1=new MaxBarcodeScanner();
//        barcodeScanner1.usebar();
//        MaxBarcodeScanner maxBarcodeScanner=new MaxBarcodeScanner();
//        maxBarcodeScanner.usebar();
//        maxBarcodeScanner.mainbar();
//        ProBarcodeScanner proBarcodeScanner=new ProBarcodeScanner();
//        proBarcodeScanner.showbar(barcodeScanner);
//        proBarcodeScanner.showbar(barcodeScanner1);50
        System.out.println("===============================================================");
        POSMachine posMachine=new POSMachine();
        posMachine.setPOSMachine(25,"Ikea");
        System.out.println(posMachine);
        posMachine.machdisp();
//        posMachine.usemachine();
//        POSMachine posMachine1=new SmartPOSMachine();
//        posMachine1.usemachine();
//        SmartPOSMachine smartPOSMachine=new SmartPOSMachine();
//        smartPOSMachine.mainmachine();
//        smartPOSMachine.usemachine();
//        ProPOSMachine posMachine2=new ProPOSMachine();
//        posMachine2.showmachine(posMachine);
//        posMachine2.showmachine(posMachine1);
        System.out.println("===============================================================");
        SmartThermostat smartThermostat=new SmartThermostat();
        smartThermostat.setSmartThermostat(32,"Hire");
        smartThermostat.thermDisp();
        System.out.println(smartThermostat);
//        smartThermostat.usesmart();
//        SmartThermostat smartThermostat1=new ProSmartThermostat();
//        smartThermostat1.usesmart();
//        ProSmartThermostat proSmartThermostat=new ProSmartThermostat();
//        proSmartThermostat.usesmart();
//        proSmartThermostat.mainsmart();
//        UltraSmartThermostat ultraSmartThermostat=new UltraSmartThermostat();
//        ultraSmartThermostat.showthermo(smartThermostat);
//        ultraSmartThermostat.showthermo(smartThermostat1);
        System.out.println("===============================================================");
        DashCam dashCam=new DashCam();
        dashCam.setDashCam("MI",1420);
        dashCam.dashDisp();
        System.out.println(dashCam);
//        dashCam.usedash();
//        DashCam dashCam1=new UltraDashCam();
//        dashCam1.usedash();
//        UltraDashCam dashCam2=new UltraDashCam();
//        dashCam2.usedash();
//        dashCam2.maindash();
//        ProDashCam proDashCam=new ProDashCam();
//        proDashCam.showdash(dashCam);
//        proDashCam.showdash(dashCam1);
        System.out.println("===============================================================");
        Soundbar soundbar=new Soundbar();
        soundbar.setSoundbar("sumsung",240);
        soundbar.soundDisp();
        System.out.println(soundbar);
//        soundbar.usesounde();
//        Soundbar soundbar1=new MaxSoundbar();
//        soundbar1.usesounde();
//        MaxSoundbar soundbar2=new MaxSoundbar();
//        soundbar2.usesounde();
//        soundbar2.mainsounder();
//        ProSoundbar proSoundbar=new ProSoundbar();
//        proSoundbar.showsound(soundbar);
//        proSoundbar.showsound(soundbar1);
        System.out.println("===============================================================");
        WalkieTalkie walkieTalkie=new WalkieTalkie();
        walkieTalkie.setWalkieTalkie(2000,"blue");
        walkieTalkie.walkDisp();
        System.out.println(walkieTalkie);
//        walkieTalkie.usewalk();
//        WalkieTalkie walkieTalkie1=new EliteWalkieTalkie();
//        walkieTalkie1.usewalk();
//        EliteWalkieTalkie eliteWalkieTalkie=new EliteWalkieTalkie();
//        eliteWalkieTalkie.mainwalk();
//        eliteWalkieTalkie.usewalk();
//        ProWalkieTalkie proWalkieTalkie=new ProWalkieTalkie();
//        proWalkieTalkie.showalkie(walkieTalkie);
//        proWalkieTalkie.showalkie(walkieTalkie1);
        System.out.println("===============================================================");
        Intercom intercom=new Intercom();
        intercom.setIntercom("airtel",120);
        intercom.interDisp();
        System.out.println(intercom);
//        intercom.useinter();
//        Intercom intercom1=new ProIntercom();
//        intercom1.useinter();
//        ProIntercom proIntercom=new ProIntercom();
//        proIntercom.useinter();
//        proIntercom.maininter();
//        UltraIntercom ultraIntercom=new UltraIntercom();
//        ultraIntercom.showinter(intercom);
//        ultraIntercom.showinter(intercom1);
        System.out.println("===============================================================");
        RiceCooker riceCooker=new RiceCooker();
        riceCooker.setRiceCooker(25,"Goodrej");
        riceCooker.riceDisp();
        System.out.println(riceCooker);
//        riceCooker.userice();
//        RiceCooker riceCooker1=new SmartRiceCooker();
//        riceCooker1.userice();
//        SmartRiceCooker smartRiceCooker=new SmartRiceCooker();
//        smartRiceCooker.userice();
//        smartRiceCooker.mainrice();
//        ProRiceCooker proRiceCooker=new ProRiceCooker();
//        proRiceCooker.showrice(riceCooker);
//        proRiceCooker.showrice(riceCooker1);
        System.out.println("===============================================================");
        SlowCooker slowCooker=new SlowCooker();
        slowCooker.setSlowCooker(25,"silver");
        slowCooker.cookDisp();
        System.out.println(slowCooker);
//        slowCooker.usecook();
//        SlowCooker slowCooker1=new UltraSlowCooker();
//        slowCooker1.usecook();
//        UltraSlowCooker ultraSlowCooker=new UltraSlowCooker();
//        ultraSlowCooker.maincook();
//        ultraSlowCooker.usecook();
//        ProSlowCooker proSlowCooker=new ProSlowCooker();
//        proSlowCooker.showslow(slowCooker);
//        proSlowCooker.showslow(slowCooker1);
        System.out.println("===============================================================");
        Juicer juicer=new Juicer();
        juicer.setJuicer("mixer",120);
        juicer.juiceDisp();
        System.out.println(juicer);
//        juicer.usejuice();
//        Juicer juicer1=new ProJuicer();
//        juicer1.usejuice();
//        ProJuicer proJuicer=new ProJuicer();
//        proJuicer.mainjuice();
//        proJuicer.usejuice();
//        UltraJuicer ultraJuicer=new UltraJuicer();
//        ultraJuicer.showjuice(juicer);
//        ultraJuicer.showjuice(juicer1);
        System.out.println("===============================================================");
        AirFryer airFryer=new AirFryer();
        airFryer.setAirFryer(120,"USHA");
        airFryer.airDisp();
        System.out.println(airFryer);
//        airFryer.useair();
//        AirFryer airFryer1=new EliteAirFryer();
//        airFryer1.useair();
//        EliteAirFryer eliteAirFryer=new EliteAirFryer();
//        eliteAirFryer.mainair();
//        eliteAirFryer.useair();
//        ProAirFryer proAirFryer=new ProAirFryer();
//        proAirFryer.showair(airFryer);
//        proAirFryer.showair(airFryer1);
        System.out.println("===============================================================");
        SandwichMaker sandwichMaker=new SandwichMaker();
        sandwichMaker.setSandwichMaker("Sharp 100",50);
        sandwichMaker.sandDisp();
        System.out.println(sandwichMaker);
//        sandwichMaker.usesand();
//        SandwichMaker sandwichMaker1=new MaxSandwichMaker();
//        sandwichMaker1.usesand();
//        MaxSandwichMaker sandwichMaker2=new MaxSandwichMaker();
//        sandwichMaker2.mainand();
//        sandwichMaker2.usesand();
//        ProSandwichMaker proSandwichMaker=new ProSandwichMaker();
//        proSandwichMaker.showsand(sandwichMaker);
//        proSandwichMaker.showsand(sandwichMaker2);
        System.out.println("===============================================================");
        WaterHeater waterHeater=new WaterHeater();
        waterHeater.setWaterHeater(50,"Solid Heat");
        waterHeater.waterDisp();
        System.out.println(waterHeater);
//        waterHeater.water();
//        WaterHeater waterHeater1=new UltraWaterHeater();
//        waterHeater1.water();
//        UltraWaterHeater waterHeater2=new UltraWaterHeater();
//        waterHeater2.mainwater();
//        waterHeater2.water();
//        ProWaterHeater proWaterHeater=new ProWaterHeater();
//        proWaterHeater.showwater(waterHeater);
//        proWaterHeater.showwater(waterHeater1);
        System.out.println("===============================================================");
        Treadmill treadmill=new Treadmill();
        treadmill.setTreadmill(120,"AirRock");
        treadmill.treadDisp();
        System.out.println(treadmill);
//        treadmill.usetread();
//        Treadmill treadmill1=new SmartTreadmill();
//        treadmill1.usetread();
//        SmartTreadmill smartTreadmill=new SmartTreadmill();
//        smartTreadmill.maintread();
//        smartTreadmill.usetread();
//        ProTreadmill proTreadmill=new ProTreadmill();
//        proTreadmill.showtread(treadmill);
//        proTreadmill.showtread(treadmill1);
        System.out.println("===============================================================");
        EllipticalTrainer ellipticalTrainer=new EllipticalTrainer();
        ellipticalTrainer.setEllipticalTrainer(90,"Rockfilter");
        ellipticalTrainer.elliDisp();
        System.out.println(ellipticalTrainer);
//        ellipticalTrainer.useelli();
//        EllipticalTrainer ellipticalTrainer1=new ProEllipticalTrainer();
//        ellipticalTrainer1.useelli();
//        ProEllipticalTrainer proEllipticalTrainer=new ProEllipticalTrainer();
//        proEllipticalTrainer.useelli();
//        proEllipticalTrainer.mainelli();
//        UltraEllipticalTrainer ultraEllipticalTrainer=new UltraEllipticalTrainer();
//        ultraEllipticalTrainer.showtrain(ellipticalTrainer);
//        ultraEllipticalTrainer.showtrain(ellipticalTrainer1);
        System.out.println("===============================================================");
        MassageChair massageChair=new MassageChair();
        massageChair.setMassageChair("model123d",200);
        massageChair.massDisp();
        System.out.println(massageChair);
//        massageChair.usemass();
//        MassageChair massageChair1=new EliteMassageChair();
//        massageChair1.usemass();
//        EliteMassageChair eliteMassageChair=new EliteMassageChair();
//        eliteMassageChair.usemass();
//        eliteMassageChair.mainmass();
//        ProMassageChair proMassageChair=new ProMassageChair();
//        proMassageChair.showmessage(massageChair);
//        proMassageChair.showmessage(massageChair1);
        System.out.println("===============================================================");
        SmartScale smartScale=new SmartScale();
        smartScale.setSmartScale(45,"Rockesz 45");
        smartScale.scaleDisp();
        System.out.println(smartScale);
//        smartScale.usesmart();
//        SmartScale smartScale1=new UltraSmartScale();
//        smartScale1.usesmart();
//        UltraSmartScale ultraSmartScale=new UltraSmartScale();
//        ultraSmartScale.mainsmart();
//        ultraSmartScale.usesmart();
//        ProSmartScale proSmartScale=new ProSmartScale();
//        proSmartScale.showsmart(smartScale);
//        proSmartScale.showsmart(smartScale1);
        System.out.println("===============================================================");
        AirHumidifier airHumidifier=new AirHumidifier();
        airHumidifier.setAirHumidifier(250,"usha");
        airHumidifier.humidDisp();
        System.out.println(airHumidifier);
//        airHumidifier.useair();
//        AirHumidifier airHumidifier1=new MaxAirHumidifier();
//        airHumidifier1.useair();
//        MaxAirHumidifier maxAirHumidifier=new MaxAirHumidifier();
//        maxAirHumidifier.mainair();
//        maxAirHumidifier.useair();
//        ProAirHumidifier proAirHumidifier=new ProAirHumidifier();
//        proAirHumidifier.showair(airHumidifier);
//        proAirHumidifier.showair(airHumidifier1);
        System.out.println("===============================================================");
        DigitalClock digitalClock=new DigitalClock();
        digitalClock.setDigitalClock("24 hours","Titan");
        digitalClock.clockDisp();
        System.out.println(digitalClock);
        //digitalClock.usedigital();
//        DigitalClock digitalClock1=new SmartDigitalClock();
//        digitalClock1.usedigital();
//        SmartDigitalClock smartDigitalClock=new SmartDigitalClock();
//        smartDigitalClock.usedigital();
//        smartDigitalClock.maindigita();
//        ProDigitalClock proDigitalClock=new ProDigitalClock();
//        proDigitalClock.showdigital(digitalClock);
//        proDigitalClock.showdigital(digitalClock1);
        System.out.println("===============================================================");
        WeatherStation weatherStation=new WeatherStation();
        weatherStation.setWeatherStation("Bengalore","infotech");
        weatherStation.weatherDisp();
        System.out.println(weatherStation);
//        weatherStation.useweather();
//        WeatherStation weatherStation1=new ProWeatherStation();
//        weatherStation1.useweather();
//        ProWeatherStation proWeatherStation=new ProWeatherStation();
//        proWeatherStation.mainweather();
//        proWeatherStation.useweather();
//        UltraWeatherStation ultraWeatherStation=new UltraWeatherStation();
//        ultraWeatherStation.showstation(weatherStation);
//        ultraWeatherStation.showstation(weatherStation1);
        System.out.println("===============================================================");
        SmartCurtain smartCurtain=new SmartCurtain();
        smartCurtain.setSmartCurtain("Red","cutton");
        smartCurtain.curtainDisp();
        System.out.println(smartCurtain);
//        smartCurtain.usesmart();
//        SmartCurtain smartCurtain1=new EliteSmartCurtain();
//        smartCurtain1.usesmart();
//        EliteSmartCurtain eliteSmartCurtain=new EliteSmartCurtain();
//        eliteSmartCurtain.usesmart();
//        eliteSmartCurtain.mainsmart();
//        ProSmartCurtain proSmartCurtain=new ProSmartCurtain();
//        proSmartCurtain.showsmart(smartCurtain);
//        proSmartCurtain.showsmart(smartCurtain1);
        System.out.println("===============================================================");
        ElectricBlanket electricBlanket=new ElectricBlanket();
        electricBlanket.setElectricBlanket(45,"Iron");
        electricBlanket.blanketDisp();
        System.out.println(electricBlanket);

//        electricBlanket.useele();
//        ElectricBlanket electricBlanket1=new UltraElectricBlanket();
//        electricBlanket1.useele();
//        UltraElectricBlanket ultraElectricBlanket=new UltraElectricBlanket();
//        ultraElectricBlanket.useele();
//        ultraElectricBlanket.mainele();
//        ProElectricBlanket proElectricBlanket=new ProElectricBlanket();
//        proElectricBlanket.showblank(electricBlanket);
//        proElectricBlanket.showblank(electricBlanket1);
        System.out.println("===============================================================");
        SmartSocket smartSocket=new SmartSocket();
        smartSocket.setSmartSocket("Rectangle",240);
        smartSocket.socketDisp();
        System.out.println(smartSocket);
//        smartSocket.usesmart();
//        SmartSocket smartSocket1=new MaxSmartSocket();
//        smartCurtain1.usesmart();
//        MaxSmartSocket maxSmartSocket=new MaxSmartSocket();
//        maxSmartSocket.mainsmart();
//        maxSmartSocket.usesmart();
//        ProSmartSocket proSmartSocket=new ProSmartSocket();
//        proSmartSocket.showsock(smartSocket);
//        proSmartSocket.showsock(smartSocket1);
        System.out.println("===============================================================");
        SmartRemote smartRemote=new SmartRemote();
        smartRemote.setSmartRemote("LG","TX1234");
        smartRemote.remoteDisp();
        System.out.println(smartRemote);
//        smartRemote.usesmart();
//        SmartRemote smartRemote1=new SmartSmartRemote();
//        smartRemote1.usesmart();
//        SmartSmartRemote smartSmartRemote=new SmartSmartRemote();
//        smartSmartRemote.mainsmart();
//        smartSmartRemote.usesmart();
//        ProSmartRemote proSmartRemote=new ProSmartRemote();
//        proSmartRemote.showremote(smartRemote);
//        proSmartRemote.showremote(smartRemote1);
        System.out.println("===============================================================");
        SmartSprinkler smartSprinkler=new SmartSprinkler();
        smartSprinkler.setSmartSprinkler("sprink",128);
        smartSprinkler.sprinklerDisp();
        System.out.println(smartSprinkler);
//        smartSprinkler.usesmart();
//        SmartSprinkler smartSprinkler1=new ProSmartSprinkler();
//        smartSprinkler1.usesmart();
//        ProSmartSprinkler proSmartSprinkler=new ProSmartSprinkler();
//        proSmartSprinkler.mainsmart();
//        proSmartSprinkler.usesmart();
//        UltraSmartSprinkler ultraSmartSprinkler=new UltraSmartSprinkler();
//        ultraSmartSprinkler.showsprink(smartSprinkler);
//        ultraSmartSprinkler.showsprink(smartSprinkler1);
        System.out.println("===============================================================");
        BabyMonitor babyMonitor=new BabyMonitor();
        babyMonitor.setBabyMonitor("Video","Night Vision");
        babyMonitor.monitorDisp();
        System.out.println(babyMonitor);
//        babyMonitor.usebaby();
//        BabyMonitor babyMonitor1=new EliteBabyMonitor();
//        babyMonitor1.usebaby();
//        EliteBabyMonitor eliteBabyMonitor=new EliteBabyMonitor();
//        eliteBabyMonitor.mainbaby();
//        eliteBabyMonitor.usebaby();
//        ProBabyMonitor proBabyMonitor=new ProBabyMonitor();
//        proBabyMonitor.showmoni(babyMonitor);
//        proBabyMonitor.showmoni(babyMonitor1);
        System.out.println("===============================================================");
        GarageDoorOpener garageDoorOpener=new GarageDoorOpener();
        garageDoorOpener.setGarageDoorOpener("Roller","steel");
        garageDoorOpener.doorDisp();
        System.out.println(garageDoorOpener);

//        garageDoorOpener.usegarage();
//        GarageDoorOpener garageDoorOpener1=new UltraGarageDoorOpener();
//        garageDoorOpener1.usegarage();
//        UltraGarageDoorOpener ultraGarageDoorOpener=new UltraGarageDoorOpener();
//        ultraGarageDoorOpener.maingarage();
//        ultraGarageDoorOpener.usegarage();
//        ProGarageDoorOpener proGarageDoorOpener=new ProGarageDoorOpener();
//        proGarageDoorOpener.showdoor(garageDoorOpener);
//        proGarageDoorOpener.showdoor(garageDoorOpener1);
        System.out.println("===============================================================");
        SmartFaucet smartFaucet=new SmartFaucet();
        smartFaucet.setSmartFaucet("Touchless","chrome");
        smartFaucet.faucetDisp();
        System.out.println(smartFaucet);
//        smartFaucet.usesmart();
//        SmartFaucet smartFaucet1=new MaxSmartFaucet();
//        smartFaucet1.usesmart();
//        MaxSmartFaucet maxSmartFaucet=new MaxSmartFaucet();
//        maxSmartFaucet.mainsmart();
//        maxSmartFaucet.usesmart();
//        ProSmartFaucet proSmartFaucet=new ProSmartFaucet();
//        proSmartFaucet.showfaucet(smartFaucet);
//        proSmartFaucet.showfaucet(smartFaucet1);
        System.out.println("===============================================================");
        SmartMat smartMat=new SmartMat();
        smartMat.setSmartMat("Yoga","mart");
        smartMat.matDisp();
        System.out.println(smartMat);
//        smartMat.usesmart();
//        SmartMat smartMat1=new SmartSmartMat();
//        sandwichMaker1.usesand();
//        SmartSmartMat smartSmartMat=new SmartSmartMat();
//        smartSmartMat.mainsmart();
//        smartSmartMat.usesmart();
//        ProSmartCurtain proSmartCurtain1=new ProSmartCurtain();
//        proSmartCurtain1.showsmart(smartCurtain);
//        proSmartCurtain1.showsmart(smartCurtain1);
        System.out.println("===============================================================");
        SmartHelmet smartHelmet=new SmartHelmet();
        smartHelmet.setSmartHelmet("Biscycle","motorcycle");
        smartHelmet.helmetDisp();
        System.out.println(smartHelmet);
//        smartHelmet.usesmart();
//        SmartHelmet smartHelmet1=new ProSmartHelmet();
//        smartHelmet1.usesmart();
//        ProSmartHelmet proSmartHelmet=new ProSmartHelmet();
//        proSmartHelmet.mainsmart();
//        proSmartHelmet.usesmart();
//        UltraSmartHelmet ultraSmartHelmet=new UltraSmartHelmet();
//        ultraSmartHelmet.showhel(smartHelmet);
//        ultraSmartHelmet.showhel(smartHelmet1);
        System.out.println("===============================================================");
        VRHeadset vrHeadset=new VRHeadset();
        vrHeadset.setVRHeadset("bass","apple");
        vrHeadset.headsetDisp();
        System.out.println(vrHeadset);
//        vrHeadset.usehead();
//        VRHeadset vrHeadset1=new EliteVRHeadset();
//        vrHeadset1.usehead();
//        EliteVRHeadset eliteVRHeadset=new EliteVRHeadset();
//        eliteVRHeadset.mainhead();
//        eliteVRHeadset.usehead();
//        ProVRHeadset proVRHeadset=new ProVRHeadset();
//        proVRHeadset.showvr(vrHeadset);
//        proVRHeadset.showvr(vrHeadset1);
        System.out.println("===============================================================");
        DronePro dronePro=new DronePro();
        dronePro.setDronePro("DJI Mavic Pro","phantom 4");
        dronePro.droneDisp();
        System.out.println(dronePro);

//        dronePro.usedrone();
//        DronePro dronePro1=new UltraDronePro();
//        dronePro1.usedrone();
//        UltraDronePro ultraDronePro=new UltraDronePro();
//        ultraDronePro.maindrone();
//        ultraDronePro.usedrone();
        System.out.println("===============================================================");
        ActionCamera actionCamera=new ActionCamera();
        actionCamera.setActionCamera("4K","1020P");
        actionCamera.actionDisp();
        System.out.println(actionCamera);
//        actionCamera.useaction();
//        ActionCamera actionCamera1=new MaxActionCamera();
//        actionCamera1.useaction();
//        MaxActionCamera maxActionCamera=new MaxActionCamera();
//        maxActionCamera.useaction();
//        maxActionCamera.mainaction();
//        ProActionCamera proActionCamera=new ProActionCamera();
//        proActionCamera.showcam(actionCamera);
//        proActionCamera.showcam(actionCamera1);
        System.out.println("===============================================================");
        ElectricGrill electricGrill=new ElectricGrill();
        electricGrill.setElectricGrill("Asus",35);
        electricGrill.grillDisp();
        System.out.println(electricGrill);
//        electricGrill.useele();
//        ElectricGrill electricGrill1=new SmartElectricGrill();
//        electricGrill1.useele();
//        SmartElectricGrill smartElectricGrill=new SmartElectricGrill();
//        smartElectricGrill.useele();
//        smartElectricGrill.mainele();
//        ProElectricGrill proElectricGrill=new ProElectricGrill();
//        proElectricGrill.showgrill(electricGrill);
//        proElectricGrill.showgrill(electricGrill1);
        System.out.println("===============================================================");
        ProjectorPro projectorPro=new ProjectorPro();
        projectorPro.setProjectorPro("Epson",1020);
        projectorPro.projectorDisp();
        System.out.println(projectorPro);
//        projectorPro.usepro();
//        ProjectorPro projectorPro1=new ProProjectorPro();
//        projectorPro.usepro();
//        ProProjectorPro proProjectorPro=new ProProjectorPro();
//        proProjectorPro.usepro();
//        proProjectorPro.mainpro();
//        SmartProjectorPro smartProjectorPro=new SmartProjectorPro();
//        smartProjectorPro.shoepro(projectorPro);
//        smartProjectorPro.shoepro(projectorPro1);
        System.out.println("===============================================================");
        DigitalMicroscope digitalMicroscope=new DigitalMicroscope();
        digitalMicroscope.setDigitalMicroscope("nikon",100);
        digitalMicroscope.microscopeDisp();
        System.out.println(digitalMicroscope);
//        digitalMicroscope.usedigital();
//        DigitalMicroscope digitalMicroscope1=new EliteDigitalMicroscope();
//        digitalMicroscope1.usedigital();
//        EliteDigitalMicroscope eliteDigitalMicroscope=new EliteDigitalMicroscope();
//        eliteDigitalMicroscope.usedigital();
//        eliteDigitalMicroscope.maindigital();
//        ProDigitalMicroscope proDigitalMicroscope=new ProDigitalMicroscope();
//        proDigitalMicroscope.showmicro(digitalMicroscope);
//        proDigitalMicroscope.showmicro(digitalMicroscope1);
        System.out.println("===============================================================");
        SmartNotebook smartNotebook=new SmartNotebook();
        smartNotebook.setSmartNotebook("HP",256);
        smartNotebook.notebookDisp();
        System.out.println(smartNotebook);
//        smartNotebook.usesmart();
//        SmartNotebook smartNotebook1=new UltraSmartNotebook();
//        smartNotebook1.usesmart();
//        UltraSmartNotebook ultraSmartNotebook=new UltraSmartNotebook();
//        ultraSmartNotebook.usesmart();
//        ultraSmartNotebook.mainsmart();
//        ProSmartNotebook proSmartNotebook=new ProSmartNotebook();
//        proSmartNotebook.shownote(smartNotebook);
//        proSmartNotebook.shownote(smartNotebook1);
        System.out.println("===============================================================");
        BloodPressureMonitor bloodPressureMonitor=new BloodPressureMonitor();
        bloodPressureMonitor.setBloodPressureMonitor("Omron",12);
        bloodPressureMonitor.monitorDisp();
        System.out.println(bloodPressureMonitor);
//        bloodPressureMonitor.useblood();
//        BloodPressureMonitor bloodPressureMonitor1=new SmartBloodPressureMonitor();
//        bloodPressureMonitor1.useblood();
//        SmartBloodPressureMonitor smartBloodPressureMonitor=new SmartBloodPressureMonitor();
//        smartBloodPressureMonitor.useblood();
//        smartBloodPressureMonitor.mainblood();
//        ProBloodPressureMonitor proBloodPressureMonitor=new ProBloodPressureMonitor();
//        proBloodPressureMonitor.showblood(bloodPressureMonitor);
//        proBloodPressureMonitor.showblood(bloodPressureMonitor1);
        System.out.println("===============================================================");
        ECGMonitor ecgMonitor=new ECGMonitor();
        ecgMonitor.setECGMonitor("Philips",9);
        ecgMonitor.monitorDisp();
        System.out.println(ecgMonitor);
//        ecgMonitor.useecg();
//        ECGMonitor ecgMonitor1=new ProECGMonitor();
//        ecgMonitor1.useecg();
//        ProECGMonitor proECGMonitor=new ProECGMonitor();
//        proECGMonitor.useecg();
//        proECGMonitor.mainecg();
//        SmartECGMonitor smartECGMonitor=new SmartECGMonitor();
//        smartECGMonitor.showmoni(ecgMonitor);
//        smartECGMonitor.showmoni(ecgMonitor1);
        System.out.println("===============================================================");
        GlucoseMonitor glucoseMonitor=new GlucoseMonitor();
        glucoseMonitor.setGlucoseMonitor("Pruthvi check",12);
        glucoseMonitor.monitorDisp();
        System.out.println(glucoseMonitor);
//        glucoseMonitor.useglu();
//        GlucoseMonitor glucoseMonitor1=new EliteGlucoseMonitor();
//        glucoseMonitor1.useglu();
//        EliteGlucoseMonitor eliteGlucoseMonitor=new EliteGlucoseMonitor();
//        eliteGlucoseMonitor.mainglu();
//        eliteGlucoseMonitor.useglu();
//        SmartGlucoseMonitor smartGlucoseMonitor=new SmartGlucoseMonitor();
//        smartGlucoseMonitor.showglucose(glucoseMonitor);
//        smartGlucoseMonitor.showglucose(glucoseMonitor1);
        System.out.println("===============================================================");
        SmartShoe smartShoe=new SmartShoe();
        smartShoe.setSmartShoe("Nike","10");
        smartShoe.shoeDetails();
        System.out.println(smartShoe);
//        smartShoe.usesmart();
//        SmartShoe smartShoe1=new UltraSmartShoe();
//        smartShoe1.usesmart();
//        UltraSmartShoe ultraSmartShoe=new UltraSmartShoe();
//        ultraSmartShoe.mainsmart();
//        ultraSmartShoe.usesmart();
//        ProSmartShoe proSmartShoe=new ProSmartShoe();
//        proSmartShoe.showsmart(smartShoe);
//        proSmartShoe.showsmart(smartShoe1);
        System.out.println("===============================================================");
        SmartTrashCan smartTrashCan=new SmartTrashCan();
        smartTrashCan.setSmartTrashCan("Black",30);
        smartTrashCan.trashDetails();
        System.out.println(smartTrashCan);
//        smartTrashCan.usesmart();
//        SmartTrashCan smartTrashCan1=new SmartSmartTrashCan();
//        smartTrashCan1.usesmart();
//        SmartSmartTrashCan smartSmartTrashCan=new SmartSmartTrashCan();
//        smartSmartTrashCan.mainsmart();
//        smartSmartTrashCan.usesmart();
//        ProSmartTrashCan proSmartTrashCan=new ProSmartTrashCan();
//        proSmartTrashCan.showsmart(smartTrashCan);
//        proSmartTrashCan.showsmart(smartTrashCan1);
        System.out.println("===============================================================");
        SmartPen smartPen=new SmartPen();
        smartPen.setSmartPen("Blue","Pilot");
        smartPen.penDetails();
        System.out.println(smartPen);
//        smartPen.usepen();
//        SmartPen smartPen1=new EliteSmartPen();
//        smartPen1.usepen();
//        EliteSmartPen eliteSmartPen=new EliteSmartPen();
//        eliteSmartPen.usepen();
//        eliteSmartPen.mainpen();
//        ProSmartPen proSmartPen=new ProSmartPen();
//        proSmartPen.showsmart(smartPen);
//        proSmartPen.showsmart(smartPen1);
        System.out.println("===============================================================");
        WindowCleaner windowCleaner=new WindowCleaner();
        windowCleaner.setWindowCleaner("life 123",12);
        windowCleaner.cleanerDetails();
        System.out.println(windowCleaner);

//        windowCleaner.usewindow();
//        WindowCleaner windowCleaner1=new MaxWindowCleaner();
//        windowCleaner1.usewindow();
//        MaxWindowCleaner maxWindowCleaner=new MaxWindowCleaner();
//        maxWindowCleaner.usewindow();
//        maxWindowCleaner.mainwindow();
//        ProWindowCleaner proWindowCleaner=new ProWindowCleaner();
//        proWindowCleaner.showwind(windowCleaner);
//        proWindowCleaner.showwind(windowCleaner1);
        System.out.println("===============================================================");
        SmartTowel smartTowel=new SmartTowel();
        smartTowel.setSmartTowel("Cutton","ullas");
        smartTowel.towelDetails();
        System.out.println(smartTowel);
//        smartTowel.usetowel();
//        SmartTowel smartTowel1=new SmartSmartTowel();
//        smartTowel1.usetowel();
//        SmartSmartTowel smartSmartTowel=new SmartSmartTowel();
//        smartSmartTowel.usetowel();
//        smartSmartTowel.maintowel();
//        ProSmartTowel proSmartTowel=new ProSmartTowel();
//        proSmartTowel.showsmart(smartTowel);
//        proSmartTowel.showsmart(smartTowel1);
    }
}
